apiVersion: 1

datasources:
  - name: SIEM SQLite
    type: fr-ser-sqlite-datasource
    uid: P1809F7DD0D724D3B
    access: proxy
    url: /data/siem_analyzer.db
    isDefault: true
    editable: true
